import fs from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
import {gzipSync,brotliCompressSync,constants} from 'node:zlib';
const require=createRequire(import.meta.url);
// The fallbacks only support building in the original export workspace; normal npm install uses standard resolution.
async function dependency(name){try{return require(name)}catch{const entries=await fs.readdir('node_modules/.pnpm');const folder=entries.find(x=>x.startsWith(name+'@'));return require(path.resolve('node_modules/.pnpm',folder,'node_modules',name))}}
const esbuild=await dependency('esbuild'),sharp=await dependency('sharp');
await fs.mkdir('public/en',{recursive:true});await fs.mkdir('public/assets',{recursive:true});await fs.mkdir('.build',{recursive:true});
await esbuild.build({entryPoints:['src/App.tsx'],outfile:'.build/App.mjs',bundle:true,platform:'node',format:'esm',jsx:'automatic',external:['react','react-dom','lucide-react'],define:{'process.env.NODE_ENV':'"production"'}});
const {default:App,ideas}=await import(path.resolve('.build/App.mjs')+'?'+Date.now());
const React=require('react'),{renderToString}=require('react-dom/server');
const client=await esbuild.build({entryPoints:['src/client.tsx'],bundle:true,minify:true,format:'esm',jsx:'automatic',target:['es2020'],write:false,legalComments:'eof',define:{'process.env.NODE_ENV':'"production"'}});
const js=client.outputFiles[0].contents;const hash=b=>createHash('sha256').update(b).digest('hex').slice(0,12);
const jsName=`app-${hash(js)}.js`;await fs.writeFile('public/assets/'+jsName,js);
const css=esbuild.transformSync(await fs.readFile('src/fonts.css','utf8')+'\n'+await fs.readFile('src/styles.css','utf8'),{loader:'css',minify:true}).code;
const cssName=`site-${hash(css)}.css`;await fs.writeFile('public/assets/'+cssName,css);
for(const [name,widths] of [['people-hero',[640,1280,1672]],['people-play',[640,1280,1536]]]){
 for(const width of widths)await sharp('src/images/'+name+'.webp').resize({width,withoutEnlargement:true}).webp({quality:80,effort:6}).toFile(`public/assets/${name}-${width}.webp`);
}
await sharp('src/images/people-hero.webp').resize(1200,630,{fit:'cover'}).jpeg({quality:84,mozjpeg:true}).toFile('public/assets/share.jpg');
const origin='https://live.asem.work';
const titles={ar:'LiveLayer من Almond Lab | أفكار تفاعلية لفعاليتك',en:'LiveLayer by Almond Lab | Interactive Event Experience Ideas'};
const descriptions={ar:'اكتشف 12 فكرة لتجربة ضيوف فعاليتك: جواز التجربة، مغامرات الاكتشاف، تفاعل الجمهور والمساعد الذكي. جرّب التصوّرات واحجز محادثة مع Almond Lab.',en:'Explore 12 interactive ideas for your next event: guest passports, discovery quests, live polls and an event guide. Try the concepts and plan with Almond Lab.'};
const escape=s=>s.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
for(const lang of ['ar','en']){
 const url=origin+(lang==='ar'?'/':'/en/');const ar=lang==='ar';
 const schema={'@context':'https://schema.org','@graph':[
 {'@type':'Organization','@id':origin+'/#organization',name:'Almond Lab',url:'https://lab.almond.sa',logo:origin+'/livelayer-logo-dark.svg'},
 {'@type':'WebSite','@id':origin+'/#website',url:origin+'/',name:'Almond LiveLayer',inLanguage:['ar','en'],publisher:{'@id':origin+'/#organization'}},
 {'@type':'WebPage','@id':url+'#webpage',url,name:titles[lang],description:descriptions[lang],inLanguage:lang,isPartOf:{'@id':origin+'/#website'},about:{'@id':origin+'/#concept'},primaryImageOfPage:{'@type':'ImageObject',url:origin+'/assets/share.jpg',caption:ar?'تصوّر بصري مولّد للفكرة، وليس توثيقاً لتجربة فعلية':'AI-generated concept visualization, not evidence of a real user test'}},
 {'@type':'CreativeWork','@id':origin+'/#concept',name:'Almond LiveLayer',description:ar?'تصوّر لطبقة تجربة رقمية قابلة للتخصيص للفعاليات. العروض والنماذج والبيانات توضيحية؛ النطاق والتكاملات تُحدّد مع كل مشروع.':'A concept for a customizable digital experience layer for events. Demos and data are illustrative; scope and integrations are defined for each project.',creator:{'@id':origin+'/#organization'}},
 {'@type':'ItemList',name:ar?'أفكار يمكن إضافتها إلى فعاليتك':'Ideas you could add to your event',numberOfItems:12,itemListElement:ideas.map((idea,i)=>({'@type':'ListItem',position:i+1,name:ar?idea.ar:idea.en,description:ar?idea.descAr:idea.descEn}))}
 ]};
 const html=`<!doctype html><html lang="${lang}" dir="${ar?'rtl':'ltr'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${titles[lang]}</title><meta name="description" content="${escape(descriptions[lang])}"><meta name="robots" content="index,follow,max-image-preview:large"><meta name="theme-color" content="#1d1825"><link rel="canonical" href="${url}"><link rel="alternate" hreflang="ar" href="${origin}/"><link rel="alternate" hreflang="en" href="${origin}/en/"><link rel="alternate" hreflang="x-default" href="${origin}/"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><meta property="og:type" content="website"><meta property="og:site_name" content="Almond LiveLayer"><meta property="og:title" content="${titles[lang]}"><meta property="og:description" content="${escape(descriptions[lang])}"><meta property="og:url" content="${url}"><meta property="og:locale" content="${ar?'ar_SA':'en_US'}"><meta property="og:locale:alternate" content="${ar?'en_US':'ar_SA'}"><meta property="og:image" content="${origin}/assets/share.jpg"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="AI-generated concept scene of guests using LiveLayer"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${titles[lang]}"><meta name="twitter:description" content="${escape(descriptions[lang])}"><meta name="twitter:image" content="${origin}/assets/share.jpg"><link rel="preload" as="font" href="/assets/${ar?'alexandria':'manrope'}-400.woff2" type="font/woff2" crossorigin><link rel="preload" as="font" href="/assets/${ar?'alexandria':'manrope'}-600.woff2" type="font/woff2" crossorigin><link rel="stylesheet" href="/assets/${cssName}"><script type="application/ld+json">${JSON.stringify(schema).replaceAll('<','\\u003c')}</script></head><body><div id="root">${renderToString(React.createElement(App,{initialLang:lang}))}</div><noscript><style>[data-reveal]{opacity:1!important;transform:none!important}.faq-item>div[hidden]{display:block}.motion-control{display:none}</style><p style="padding:24px;text-align:center">${ar?'فعّل JavaScript لتجربة العروض التفاعلية وإرسال طلب الاجتماع.':'Enable JavaScript to use the interactive demos and submit a meeting request.'}</p></noscript><script type="module" src="/assets/${jsName}"></script></body></html>`;
 await fs.writeFile(ar?'public/index.html':'public/en/index.html',html);
}
await fs.writeFile('public/robots.txt',`User-agent: *\nAllow: /\nDisallow: /api/\nSitemap: ${origin}/sitemap.xml\n`);
await fs.writeFile('public/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">${['/','/en/'].map(p=>`<url><loc>${origin}${p}</loc><xhtml:link rel="alternate" hreflang="ar" href="${origin}/"/><xhtml:link rel="alternate" hreflang="en" href="${origin}/en/"/><xhtml:link rel="alternate" hreflang="x-default" href="${origin}/"/></url>`).join('')}</urlset>`);
await fs.writeFile('public/llms.txt',`# Almond LiveLayer\n\n> A concept by Almond Lab for customizable digital guest experiences at events.\n\n- [Arabic, primary website](${origin}/)\n- [English website](${origin}/en/)\n- [Discuss an event concept](${origin}/#meeting)\n\n## Status and scope\nThis site explains possibilities, not a finished off-the-shelf product. Demos, people imagery and metrics are illustrative, not evidence of customers or trials. No pricing, delivery guarantee or unverified integrations are claimed. A meeting form saves a request; it does not confirm a meeting or send a calendar invitation.\n\n## Possible additions\n${ideas.map(i=>`### ${i.en} — ${i.ar}\n${i.descEn}\n${i.descAr}\nScope: ${i.noteEn}\n`).join('\n')}\n## Agency delivery\nBranding and the guest experience can be adapted to the event. The client and team agree on scope, permissions, content and integrations.\n`);
await fs.writeFile('public/404.html','<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>الصفحة غير موجودة | LiveLayer</title><body style="font-family:system-ui;background:#1d1825;color:#f6f5ef;text-align:center;padding:15vh 24px"><h1>الصفحة غير موجودة</h1><p>Page not found.</p><a style="color:#d8fa62" href="/">العودة للرئيسية / Home</a></body></html>');
async function compress(dir){for(const entry of await fs.readdir(dir,{withFileTypes:true})){const file=path.join(dir,entry.name);if(entry.isDirectory()){await compress(file);continue}if(!/\.(html|css|js|svg|xml|txt|json)$/.test(file))continue;const bytes=await fs.readFile(file);await fs.writeFile(file+'.gz',gzipSync(bytes,{level:9}));await fs.writeFile(file+'.br',brotliCompressSync(bytes,{params:{[constants.BROTLI_PARAM_QUALITY]:11}}))}}
await compress('public');
console.log(JSON.stringify({javascript:{file:jsName,bytes:js.length,gzip:gzipSync(js).length},css:{file:cssName,bytes:Buffer.byteLength(css),gzip:gzipSync(css).length},pages:['/','/en/'],domain:origin},null,2));
